import { ApiProperty } from '@nestjs/swagger';

export class McpResponseDto {
  @ApiProperty({ description: 'The answer generated by the LLM via MCP' })
  answer!: string;

  @ApiProperty({ description: 'List of references or source materials used for the answer', type: [Object] })
  references!: any[];

  @ApiProperty({ description: 'Any attachments or tool output metadata', type: [Object] })
  attachments!: any[];
  
  @ApiProperty({ description: 'Confidence score if available', required: false })
  confidence?: number;
  
  @ApiProperty({ description: 'Response status', required: false })
  status?: string;
}

export type McpStreamEvent =
  | { type: 'metadata'; conversationId: string; userMessageId: string }
  | { type: 'sources'; sources: any[]; confidence: number; status: string }
  | { type: 'delta'; text: string }
  | { type: 'node'; name: string; status: 'start' | 'end' }
  | { type: 'done'; assistantMessageId: string }
  | { type: 'error'; message: string };
